### ISSUE TITLE
C-LINE (treehug) errors View and modify roads

### ISSUE THREAD

**Issue by joellenb** [CEMPD/ctools#19]
When screen comes up the traffic speeds are shown to the nearest integer. But when hover over one of the values (see 23) get popup error message "Please select a valid value. The two nearest valid values are 20 and 25. And the cursor up/down arrows in the widget do nothing.
![c-line_viewmodrdsupdnerror_12162014](https://cloud.githubusercontent.com/assets/10145737/5458794/2c0b199e-8523-11e4-9128-f6317a7912ba.PNG)

**Comment by michellegrace** [comment]
This works on my web browser... Jo Ellen can you verify that this has been fixed?

**Comment by michellegrace** [comment]
This is still an issue for the firefox browser. I do not get this error message when using safari.

**Comment by joellenb** [comment]
This is still a problem using the latest Firefox release (35.0) under 64-bit Windows 7 (both professional at work and home at home).

**Comment by cseppan** [comment]
Currently, the increment for the speed inputs is 5, with minimum value = 0. This means that only multiples of 5 are considered valid by the browser. In Firefox, this causes the input element to display with a red ring, and stops the up and down arrows from working. Safari handles the "invalid" numbers differently, and doesn't disable the increment/decrement arrows.

For now, I did the simple fix of setting the increment to 1 for the speeds. This means values like 23 are valid, so Firefox won't disable the arrows. The downside is that changing the speed by larger amounts requires the user to click the arrow more times (or type in the new speed).

**Comment by michellegrace** [comment]
Catherine, 
This is a good solution. I think we need to educate the user that there speed bins are 5mph… so changing by 1 mph with each click does not necessarily change the emission (speed bin) unless it makes you closer to the next bin than the previous bin.

Let's make sure this is in the help menu… 

I am reopening this issue, so you have it on your list to update the help menu here.

Currently the help menu text is "Miles Per Hour (MPH) represents the speeds on the link for each of four time periods." 

I suggest changing this to "Miles Per Hour (MPH) represents the average speed on the roadway. This value is used to determine emissions for each vehicle type on the roadway. Emissions are calculated in 5 MPH-bins, the closest bin to the input speed is used. These bins are 0, 5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, and 75  MPH."

-Michelle

**Comment by joellenb** [comment]
Made the change in the help file as noted in the last paragraph (above).
