### ISSUE TITLE
New color scale for comparison plots (transparent at zero).

### ISSUE THREAD

**Issue by michellegrace** [CEMPD/ctools#61]
For comparison plots the color scale should be transparent at 0. Then go from yellow to orange to red if positive difference, representing a "hot scale".  On the flip side, a color scale from green to blue to purple for negative differences would represent a "cold" scale. 

This would provide a color scheme so increased exposures would be "hot" and decreased exposures would be "cold".

**Comment by nathan-rice** [comment]
The critical label is for bug fixes that make the product unsuitable for release.  If you use it on every interface tweak issue you open it becomes meaningless to me.

**Comment by michellegrace** [comment]
As stated before, these critical labels are for things we need fixed before the release. These are typically enhancements or fixes a at essential for the user’s understanding.

There are many issues that do not have this label and those can wait for a future release, as they are not essential for a augers understanding.

-Michelle
------------------------------------------------------------------
Michelle G. Snyder, Environmental Modeler
Institute for the Environment/CEMPD
University of North Carolina at Chapel Hill
Campus Box 1105 (27599-1105)
Europa Center Suite 490 Rm. 4052
100 Europa Dr.
Chapel Hill, NC 27517

phone: 919-843-7561
email: michellesnyder@unc.edu<mailto:michellesnyder@unc.edu>

**Comment by nathan-rice** [comment]
You are confusing "would be nice" with "must have".  I gave you guys the critical label as a way to "rush order" something that was a show stopper, at the expense of time I devote to other clients, so you guys can have a quick release.  It is currently being placed on pretty much every issue being created, including things that are outside the scope of what Sarav said he needed in place for a release.

If the abuse of the tag continues I will just treat critical issues like regular issues, and balance them with work from other clients.

**Comment by arunacs** [comment]
That is right Nathan. While I agree that it can be annoying to see Critical on all our recent issue posts, I have asked our team to only report things that need to be fixed before our long-due release. I think we have an excellent tool that is likely going to get a lot of wide exposure (pun intended). However,  since we are releasing to a broader audience, we want to make sure that the first impression is the best impression for the most part. Thanks for your indulgence during this phase, and we will continue to use this a bit more judiciously going forward.

**Comment by nathan-rice** [comment]
Regardless, this issue in particular is a perfect example of what should *not* be marked critical.  You want a new feature, which is fine, but you don't know how much work is involved.  Implementing this isn't just a one line fix (otherwise I wouldn't make a stink), the mechanism to control the alpha of a heatmap is rather convoluted, unfortunately - it isn't a supported feature, I have to hack the internals of the library to get it to render that way.

Ultimately, it's just an issue of fairness.  Just imagine if I gave another client a way to shortcut the line and they started using it for everything, so your work took forever to turn around - you wouldn't like it would you?  I personally don't care what it is I'm working on, but I feel terrible telling clients they are getting bumped.

**Comment by michellegrace** [comment]
I would be happy with it as we currently have where we have a + and – scale with the current scheme. You asked Sarav for his opinion and he stated that the 2-part color scale is what he wants, thus the critical label on the new issue.

-Michelle
------------------------------------------------------------------
Michelle G. Snyder, Environmental Modeler
Institute for the Environment/CEMPD
University of North Carolina at Chapel Hill
Campus Box 1105 (27599-1105)
Europa Center Suite 490 Rm. 4052
100 Europa Dr.
Chapel Hill, NC 27517

phone: 919-843-7561
email: michellesnyder@unc.edu<mailto:michellesnyder@unc.edu>

**Comment by michellegrace** [comment]
I used the Raleigh case where I decreased the AADT on US1 southwest of Raleigh. I added to this, an increase in AADT on I40 west of raleigh: 
![screen shot 2015-01-28 at 12 13 52 pm](https://cloud.githubusercontent.com/assets/10077162/5943259/618faaa0-a6eb-11e4-832d-4341cd0aed4c.png)

I am testing how the color scale looks with both + and -  differences... 

the relative difference: 
![screen shot 2015-01-28 at 12 16 13 pm](https://cloud.githubusercontent.com/assets/10077162/5943268/7fe7b02e-a6eb-11e4-9298-4d8ee8fdd3f2.png)

the relative % difference: 
![screen shot 2015-01-28 at 12 29 24 pm](https://cloud.githubusercontent.com/assets/10077162/5943270/866b6d78-a6eb-11e4-8013-2f3f753b72ba.png)

these look awesome!.. HOWEVER, I went back to just decreasing the stretch of US southwest of Raleigh and I am not happy with the color scale here.

For difference I get: 
![screen shot 2015-01-28 at 12 40 39 pm](https://cloud.githubusercontent.com/assets/10077162/5943298/c88e0e36-a6eb-11e4-9250-0bcdd4e3d714.png)

For % difference I get:
![screen shot 2015-01-28 at 12 42 03 pm](https://cloud.githubusercontent.com/assets/10077162/5943302/d03b878a-a6eb-11e4-9d6a-68ef18fda053.png)

The scale when there is just and increase (or just a decrease) in concentration still goes from blue to red. If there is a negative difference only, the scale should go from blue to green as it approaches zero and becomes transparent, if there is only a positive difference the scale should go from transparent yellow to red as the difference increases. ... If I was doing this, I might find the maximum of the absolute value of the differences, say X, and have the scale go from -X to +X so it would look like the scale in the plot with both positive and negative values. If this was a percent I would take the extra step to limit this to X = 100 max so the scale would go from +100% to -100%.

**Comment by nathan-rice** [comment]
There is a pretty easy way to force 0 to be in the middle of the scale, however there is a downside to it - if you have very large changes on one side of zero, and other small changes on the other side of zero (say you increase aadt by 10x for some roads and decrease it by 50% for others) the smaller change will be "washed out" by shifting 0 to the center of the scale.

If you're ok with that, I can push up a quick tweak to make it work the way you requested.  Otherwise that feature is probably a no-go.

**Comment by nathan-rice** [comment]
Done

**Comment by michellegrace** [comment]
This color scale is still not what we discussed on Thursday. The zero needs to always be in the middle of the scale, and transparent. This means relative increases re shown int he “hot” colors, and decreases are shown in “cold” colors.

This is how an AADT increase is currently displayed.[cid:C1858D74-E2B4-4A98-91F2-34EB453D9993]


Thanks.
-Michelle
------------------------------------------------------------------
Michelle G. Snyder, Environmental Modeler
Institute for the Environment/CEMPD
University of North Carolina at Chapel Hill
Campus Box 1105 (27599-1105)
Europa Center Suite 490 Rm. 4052
100 Europa Dr.
Chapel Hill, NC 27517

phone: 919-843-7561
email: michellesnyder@unc.edu<mailto:michellesnyder@unc.edu>

**Comment by michellegrace** [comment]
Here is the screenshot, it did not upload properly when I sent my response by email.

![screen shot 2015-02-02 at 12 38 06 pm](https://cloud.githubusercontent.com/assets/10077162/6005659/1523c438-aada-11e4-9d73-c4d3a5f274ed.png)

**Comment by nathan-rice** [comment]
Fixed

**Comment by michellegrace** [comment]
This appears to be working in most cases. However, I ran 2 scenarios for Atlanta and I only hanged the met condition from stable to convective. The color scale is transparent at ~-35%, this should be 0% where the scale is transparent with a + and - difference equally on both sides of zero. 
![Uploading Screen Shot 2015-02-10 at 9.02.56 AM.png . . .]()

**Comment by michellegrace** [comment]
Let me try to upload that image again:
![screen shot 2015-02-10 at 9 02 56 am](https://cloud.githubusercontent.com/assets/10077162/6128766/c79e0b46-b106-11e4-8eb6-714482fcf13a.png)

**Comment by nathan-rice** [comment]
I fixed the issue causing asymmetry around zero, but the plot is still mostly blue and I want to verify that this is expected behavior before I push a fix to treehug.

**Comment by michellegrace** [comment]
Yes, the plot should be mostly zero, as there is a decrease in concentration. However, there is another issue that comes up with the absolute difference, see here:
![screen shot 2015-02-10 at 8 57 06 am](https://cloud.githubusercontent.com/assets/10077162/6131786/7a571024-b11c-11e4-9254-a56a6f2228a3.png)

Here the scale is linear and this washes out differences. Ideally there should be a log-scale on both sides of zero. This is problematic since log(negative number) & log (zero) is undefined. We may need to work on how to display this difference to the user, since the individual hours are shown with a log scale. I am working through how to do this on Matlab, I will get back to you with a possible solution as soon as possible.

**Comment by michellegrace** [comment]
Nathan,
I have found a solution for the color scaling in the absolute difference plots. We need to make this a log-based scaling in both the positive and negative direction.  This is problematic because negative numbers and zero are undefined for a log function. This can be over come by making these results fall into 1 of 3 regions: 

Assume: ConcDiff =  Conc2-Conc1;

(region 1)When the magnitude difference is less than 1: logConcDiff(abs(ConcDiff)<=1) = 0;

(region 2)When the difference is greater than 1 : logConcDiff(ConcDiff>1) = log10(ConcDiff(ConcDiff>1));

(region 3)When the difference is less than –1: logConcDiff(ConcDiff<-1) = -1.*log10(abs(ConcDiff(ConcDiff<-1)));

Then when you plot the realists, you plot –5  as –1x10^5, -2 as –1x10^-2, 0 as 0, and 1 as 1x10, 2 as 1x10^2, etc.

The drawback here is that we essentially setting all differences less than 1 ppb (or microgram/m^3) to zero. However, this gives a log-scale spacing of the results that will compare better with the hourly results than the linear spacing as before. This will allow the user to focus on large positive or large negative differences.

I ran this for the Atlanta case above and made an offline interpolated image: 
![diff_convvsstablesummer_intoutputs_log](https://cloud.githubusercontent.com/assets/10077162/6147275/9d984d80-b1c3-11e4-835b-db67ff4b3af1.png)

The % difference plots stay as you have them currently. Let me know if you have any questions.

**Comment by nathan-rice** [comment]
Implemented.  Try a relative run and close this issue if it works as expected.

**Comment by michellegrace** [comment]
This is close to the desired result. However, the negative numbers should be negative in front of the 10, i.e. "-10^0.76" instead of "10^-0.76". You can see the current color scale in this screenshot: 
![screen shot 2015-02-12 at 2 22 11 pm](https://cloud.githubusercontent.com/assets/10077162/6175229/d7d2f28e-b2c2-11e4-9455-853eba456912.png)

**Comment by nathan-rice** [comment]
Changed.

**Comment by michellegrace** [comment]
This looks great! I am closing this issue.

**Comment by arunacs** [comment]
The legend box with fractional exponents is not an intuitive feature for the target audience this tool is intended for. Please rework this to use only whole numbers as exponents.

**Comment by michellegrace** [comment]
The center of this scale is labeled as "10^0", this should actually be "0".

**Comment by nathan-rice** [comment]
It isn't zero though.  It's 1 > x > -1.

**Comment by michellegrace** [comment]
Correct it is this range, but the mid-point of this range is zero, so zero should be what is displayed on the legend.

**Comment by michellegrace** [comment]
This is displaying a zero for now, lets revisit later if needed.
